# This is a basic workflow to help you get started with Actions

name: InitialWorkflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: true
  NX_BASE: 'main'


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Defining different jobs: quality / build / deploy ...

  # Dependency job
  dependencies:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: 'npm'

      - name: Cache Node Modules
        id: node-cache
        uses: actions/cache@v3
        with:
            path: node_modules
            key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install Dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm install
  main:
    needs: dependencies
    runs-on: ubuntu-latest
    name: Nx Cloud - Main Job
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
      - name: 'Initialize the Nx Cloud distributed CI run'
        run: npx nx-cloud start-ci-run --stop-agents-after="build" --agent-count=3

  agents:
    needs: main
    timeout-minutes: 15
    runs-on: ubuntu-latest
    name: Nx Cloud - Agents
    strategy:
      matrix:
        agent: [1, 2, 3]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
      - name: 'Start agent ${{ matrix.agent }}'
        run: | 
          npx nx-cloud start-agent
  commands:
    needs: main
    runs-on: ubuntu-latest
    name: Commands to be triggered
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
      - name: 'Workspace lint'
        run: npx nx-cloud record -- npx nx workspace-lint
      # - name: 'check'
      #   run: npx nx-cloud record -- npx nx format:check
      - name: 'Lint all'
        run: npx nx run-many --target=lint --all --parallel=3
      - name: 'Test all'
        run: npx nx run-many --target=test --all --parallel=3 --ci --code-coverage
      - name: 'Build all'
        run: npx nx run-many --target=build --all --parallel=3


  # Quality job
  # quality:
  #   needs: dependencies
  #   # The type of runner that the job will run on
  #   runs-on: ubuntu-latest

  #   # Steps represent a sequence of tasks that will be executed as part of the job
  #   steps:
  #     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
  #     - uses: actions/checkout@v3
  #     - uses: actions/cache@v3
  #       with:
  #         path: node_modules
  #         key: node-modules-${{ hashFiles('package-lock.json') }}


      # Nx workspace-lint
  #     - name: Running workspace-lint
  #       run: npx nx workspace-lint
  #     # Nx lint
  #     - name: Running linter
  #       run: npx nx run-many --target=lint --all
  #     # Nx test
  #     - name: Running all tests
  #       run: npx nx run-many --target=test --all

  # # Build job
  # build:
  #   needs: quality
  #   # The type of runner that the job will run on
  #   runs-on: ubuntu-latest

  #   # Steps represent a sequence of tasks that will be executed as part of the job
  #   steps:
  #     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
  #     - uses: actions/checkout@v3
  #     - uses: actions/cache@v3
  #       with:
  #         path: node_modules
  #         key: node-modules-${{ hashFiles('package-lock.json') }}

  #     # Nx build
  #     - name: Running build
  #       run: npx nx build


